import { Figurine } from './figurine';

export const FIGURINES: Figurine[] = [
    {
        id: 1,
        name: "Abraracourcix",
        picture: "./assets/image/Abraracourcix.jpg",
        price: 10,
        description: "Chef du «Village des fous».",
        detail: "Figurine faite à la main",
        dimension: "Hauteur 10 cm",
    },
    {
        id: 2,
        name: "Asterix",
        picture: "./assets/image/Asterix.jpg",
        price: 12,
        description: "Mythe, copain d’Obélix.",
        detail: "Figurine faite à la main",
        dimension: "Hauteur 10 cm",
    },
    {
        id: 3,
        name: "Obelix",
        picture: "./assets/image/Obelix.jpg",
        price: 12,
        description: "Copain d’Astérix.",
        detail: "Figurine faite à la main",
        dimension: "Hauteur 10 cm",
    },
    {
        id: 4,
        name: "Idéfix",
        picture: "./assets/image/Idefix.jpg",
        price: 12,
        description: "Agent de l’environnement.",
        detail: "Figurine faite à la main",
        dimension: "Hauteur 7 cm",
    },
    {
        id: 5,
        name: "Agecanonix",
        picture: "./assets/image/Agecanonix.jpg",
        price: 10,
        description: "Doyen du village.",
        detail: "Figurine faite à la main",
        dimension: "Hauteur 10 cm",
    },
    {
        id: 6,
        name: "Panoramix",
        picture: "./assets/image/Panoramix.jpg",
        price: 12,
        description: "Panoramix, notre druide.",
        detail: "Figurine faite à la main",
        dimension: "Hauteur 10 cm",
    },
    {
        id: 7,
        name: "Mme Agecanonix",
        picture: "./assets/image/MmeAgecanonix.jpg",
        price: 10,
        description: "Femme d’Agecanonix.",
        detail: "Figurine faite à la main",
        dimension: "Hauteur 10 cm",
    },
    {
        id: 8,
        name: "Assurancetourix",
        picture: "./assets/image/Assurancetourix.jpg",
        price: 10,
        description: "Barde, instituteur et souffre-douleur.",
        detail: "Figurine faite à la main",
        dimension: "Hauteur 10 cm",
    },
    {
        id: 9,
        name: "Falbala",
        picture: "./assets/image/Falbala.jpg",
        price: 10,
        description: "Egérie d’Obélix.",
        detail: "Figurine faite à la main",
        dimension: "Hauteur 10 cm",
    },
    {
        id: 10,
        name: "Cléopatre",
        picture: "./assets/image/Cléopatre.jpg",
        price: 12,
        description: "Reine des reines.",
        detail: "Figurine faite à la main",
        dimension: "Hauteur 10 cm",
    },
    {
        id: 11,
        name: "Jules César",
        picture: "./assets/image/jules-cesar.jpg",
        price: 12,
        description: "Vini,Vidi,Vici.",
        detail: "Figurine faite à la main",
        dimension: "Hauteur 10 cm",
    },
    {
        id: 12,
        name: "Centurion",
        picture: "./assets/image/Centurion.jpg",
        price: 10,
        description: "Centurion poussé à bout.",
        detail: "Figurine faite à la main",
        dimension: "Hauteur 10 cm",
    },
    {
        id: 13,
        name: "Asterix 'Collector'",
        picture: "./assets/image/Asterix-la-liberte-eclairant-le-monde.jpg",
        price: 15,
        description: "La Liberté éclairant le Monde.",
        detail: "Figurine faite à la main",
        dimension: "Hauteur 10 cm",
    },
    {
        id: 14,
        name: "Legionnaire",
        picture: "./assets/image/Legionnaire.jpg",
        price: 10,
        description: "Ami des Gaulois.",
        detail: "Figurine faite à la main",
        dimension: "Hauteur 10 cm",
    },
    {
        id: 15,
        name: "Numérobis",
        picture: "./assets/image/Numerobis.jpg",
        price: 10,
        description: "Ami d'Egypte.",
        detail: "Figurine faite à la main",
        dimension: "Hauteur 10 cm",
  },
  {
        id: 16,
        name: "Obélix a faim",
        picture: "./assets/image/Obelixetsanglier.jpg",
        price: 12,
        description: "Casse-croute pour la route.",
        detail: "Figurine faite à la main",
        dimension: "Hauteur 10 cm",
},
];
